# Generated by Django 5.0 on 2024-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('redeem_type', models.CharField(blank=True, max_length=1, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('razorpay_payment_id', models.TextField(blank=True, null=True)),
                ('razorpay_order_id', models.TextField(blank=True, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=30, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
