# Generated by Django 5.0 on 2023-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_orders_ordertracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdrAttemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('raised_date', models.TextField(blank=True, null=True)),
                ('raised_time', models.TimeField(blank=True, null=True)),
                ('action_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('action_date', models.TextField(blank=True, null=True)),
                ('action_status', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('u_address_line1', models.TextField(blank=True, null=True)),
                ('u_address_line2', models.TextField(blank=True, null=True)),
                ('updated_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('ndr_data_type', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'ndr_attemps',
                'managed': False,
            },
        ),
    ]
