# Generated by Django 5.0 on 2024-01-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_ndrattemps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_sku', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField()),
                ('product_unitprice', models.CharField(blank=True, max_length=10, null=True)),
                ('product_qty', models.CharField(blank=True, max_length=10, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('item_id', models.CharField(max_length=50)),
                ('invoice_reference_number', models.CharField(blank=True, max_length=60, null=True)),
                ('export_reference_number', models.CharField(blank=True, max_length=60, null=True)),
                ('hsn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('hts_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
